/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SpawnOptions {
  cwd?: string
  env?: Array<string>
  windowsHide?: boolean
  shell?: boolean
}
export declare function execProcess(cmd: string, args: Array<string>, options?: SpawnOptions | undefined | null): object
export declare function spawn(cmd: string, args: Array<string>, options?: SpawnOptions | undefined | null, onStdout?: (...args: any[]) => any | undefined | null, onStderr?: (...args: any[]) => any | undefined | null, onExit?: (...args: any[]) => any | undefined | null): object
export declare function killProcess(pid: number): void
